version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
  api-rate-limiter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api-rate-limiter"
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      - redis
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
